### ISSUE TITLE
Need a TOS

### ISSUE THREAD

**Issue by jalba-flexion** [flexion/msab-arts-locator#152]
There is an anchor tag that is supposed to lead to a TOS page. Need to create one.

**Comment by bdruth** [comment]
~We need to get ToS info from MNIT or MSAB - I will email to request if there's something available.~

Edit: we have a TOS page [here](https://github.com/flexion/msab-arts-locator/tree/main/src/views/TOS.jsx) - we just need to connection the anchor in the `LocationInputForm.jsx` to the `/tos` route that pulls up this view.

**Comment by bdruth** [comment]
This is already done.
