### ISSUE TITLE
Some titles in result do not open details page.

### ISSUE THREAD

**Issue by bdruth** [flexion/msab-arts-locator#169]
Need to confirm that all results yield a valid details page (there may be bad data?).

**Tasks**
* Review with XP that this is still reproducible @bdruth 
  * Get details on records that aren't working
* Consider re-loading sample data

### Original information
* Issue Title: Click on some Results title  does not open  page
* Description: Some titles when clicked on do not open to see more details

**Comment by xpmuyanja** [comment]
This is fixed. 
•	Retested using “XP Muyanja 014/15” today with a link to a website and worked. There is also an understanding that not all posts on the site have a Website. But for the new test scenario I was able to open a website.
o	This issue should be closed

**Comment by bdruth** [comment]
Thanks @xpmuyanja!
