### ISSUE TITLE
Support canceling a new record submission.

### ISSUE THREAD

**Issue by bdruth** [flexion/msab-arts-locator#170]
As an Arts Location submitter, I want a way to exit the Submit New Location workflow but continue using the app, if I change my mind about submitting a location and do not want to exit completely.

**Acceptance Criteria**:
* Arts Location submitter can take an action to return to main app without submitting new location

- [x] User Acceptance.

**Comment by xpmuyanja** [comment]
Resolved:
Retested and when user selects a "Cancel" button, when in the process of submitting a new record, page closes out and goes back to results page previously displayed.

**Comment by bdruth** [comment]
Perfect, thanks @xpmuyanja!
