### ISSUE TITLE
Improve search results UX when no results found

### ISSUE THREAD

**Issue by bdruth** [flexion/msab-arts-locator#180]
As a site user, when there are no art locations in the area I'm searching, I want to know that the search was successful, but no results were found.

**Acceptance Criteria**:
* Site user is provided feedback when a search is successful but no results were found.

**Tasks**:
- [x] Work with UX for design/messaging @uxforgood 
- [x] Implement
- [x] Test
- [x] Review
- [x] User Acceptance

**Comment by xpmuyanja** [comment]
Resolved:
Retested and the return message is informative enough for user to know the search was successful but no results to display
![Search result msg 6-29-21](https://user-images.githubusercontent.com/86261039/123803247-bf95ab00-d8b1-11eb-8430-7d252a4f2b9f.png)

**Comment by bdruth** [comment]
Thanks @xpmuyanja!
